In [3]:
!pip install pandas_ta

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from bs4 import BeautifulSoup as bs
import requests

import json

import re

import pandas_ta as ta

import  time

Requirement already satisfied: pandas_ta in /usr/local/lib/python3.10/dist-packages (0.3.14b0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandas_ta) (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas_ta) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas_ta) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas_ta) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->pandas_ta) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->pandas_ta) (1.16.0)

In [4]:
header =   {  'Accept': '*/*' ,
              'Accept-Encoding':'gzip, deflate, br,zstd' ,
              'Accept-Language': 'en-US,en;q=0.9' ,
              'Origin':'https://www.moneycontrol.com' ,
              'Priority': 'u=1, i',
              'Referer':'https://www.moneycontrol.com/',
              'Sec-Ch-Ua-Mobile':'?0' ,
              'Sec-Ch-Ua-Platform':"Windows" ,
              'Sec-Fetch-Dest':'empty' ,
              'Sec-Fetch-Mode':'cors' ,
              'Sec-Fetch-Site':'same-site' ,
              'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
              'render_js': 'True' }

In [5]:
req = requests.get('https://www.moneycontrol.com/ipo/listed-ipos/')

soup = bs(req.content, 'html.parser')

txt = soup.find_all("script" , id = "__NEXT_DATA__")[0].text

json = json.loads(txt)
final = json['props']['pageProps']['ipoTableData']['listedIpo']

ipo_data = pd.DataFrame(final)
ipo_data

,sc_id,company_name,company_code,url,ipo_type,listing_date,issue_price,issue_size,total_subs,last_price,dt_open,dt_close,listing_gain,todays_gain
0,REL01,Rulka Electricals,13530082,miscellaneous/rulkaelectricals/REL01,SME,2024-05-24,235,263952000,629.42,450.15,NaN,NaN,NaN,NaN
1,HFI02,HOAC Foods India,11290655,food-processing/hoacfoodsindia/HFI02,SME,2024-05-24,48,55440000,1834.01,126.10,NaN,NaN,NaN,NaN
2,GDGIL,Go Digit General Insurance,17155044,lifehealth-insurance/godigitgeneralinsurance/G...,Mainline,2024-05-23,272,26146458864,9.60,301.65,286.0,306.00,12.500000,5.472028
3,QLL01,Quest Laboratories,12541811,labslife-sciences-services/questlaboratories/Q...,SME,2024-05-23,97,431611200,79.29,126.35,NaN,NaN,NaN,NaN
4,IEL04,Indian Emulsifiers,11290653,miscellaneous/indianemulsifiers/IEL04,SME,2024-05-22,132,423852000,427.95,391.05,NaN,NaN,NaN,NaN
5,AMSL,ABS Marine Services,14095030,miscellaneous/absmarineservices/AMSL,SME,2024-05-21,147,962850000,133.10,221.00,NaN,NaN,NaN,NaN
6,MAI04,Mandeep Auto Industries Ltd,10670501,miscellaneous/mandeepautoindustriesltd/MAI06,SME,2024-05-21,67,252456000,72.27,58.25,NaN,NaN,NaN,NaN
7,VAL,Veritaas Advertising Ltd,17420002,miscellaneous/veritaasadvertisingltd/VAL,SME,2024-05-21,114,84816000,581.40,235.80,NaN,NaN,NaN,NaN
8,PIL09,Piotex Industries,16030604,miscellaneous/piotexindustries/PIL10,SME,2024-05-17,94,144722400,107.50,94.50,NaN,NaN,NaN,NaN
9,AFML,Aztec Fluids & Machinery,13010131,miscellaneous/aztecfluidsmachinery/AFML,SME,2024-05-17,67,241200000,203.03,69.00,NaN,NaN,NaN,NaN
10,PRL01,Premier Roadlines,17160449,miscellaneous/premierroadlines/PRL01,SME,2024-05-17,67,403608000,109.35,82.00,NaN,NaN,NaN,NaN
11,EMIL,Energy-Mission Machineries India,13510384,miscellaneous/energy-missionmachineriesindia/EMIL,SME,2024-05-16,138,411516000,298.19,356.40,NaN,NaN,NaN,NaN
12,SPL09,Silkflex Polymers,12130127,miscellaneous/silkflexpolymers/SPL02,SME,2024-05-15,52,181064000,35.12,52.00,NaN,NaN,NaN,NaN
13,AHFL,Aadhar Housing Finance,17028543,miscellaneous/aadharhousingfinance/AHFL,Mainline,2024-05-15,315,30000000240,25.49,339.00,315.0,329.45,4.587302,7.619048
14,TTL03,TBO Tek,13193121,miscellaneous/tbotek/TTL03,Mainline,2024-05-15,920,15508093160,86.70,1429.55,1419.0,1460.25,58.722826,0.743481
15,TAL,TGIF Agribusiness,11330352,agriculture/tgifagribusiness/TAL,SME,2024-05-15,93,63946800,37.19,98.21,NaN,NaN,NaN,NaN
16,FTL02,Finelistings Technologies,13193122,miscellaneous/finelistingstechnologies/FTL02,SME,2024-05-14,123,135300000,35.52,124.45,NaN,NaN,NaN,NaN
17,WEL,Winsol Engineers,13521211,miscellaneous/winsolengineers/WEL,SME,2024-05-14,75,244632000,635.71,434.00,NaN,NaN,NaN,NaN
18,R09,Refractory Shapes,11590026,miscellaneous/refractoryshapes/R07,SME,2024-05-14,31,186000000,237.11,127.95,NaN,NaN,NaN,NaN
19,IL06,Indegene,11140174,miscellaneous/indegene/IL05,Mainline,2024-05-13,452,18417594732,69.91,525.00,655.0,570.90,26.305310,-19.847328

In [6]:
url1  =  'https://query2.finance.yahoo.com/v8/finance/chart/'
url2  =  '.NS?period1=1716443400&period2=1716737400&interval=1h&'
url3  =  'includePrePost=true&events=div%7Csplit%7Cearn&useYfid=true&lang=en-US&region=US'

In [7]:
for ind, stk in enumerate(ipo_data.company_name) :

  url_com = ipo_data.iloc[ind]['url']
  url_com =  'https://www.moneycontrol.com/india/stockpricequote/' + url_com

  req = requests.get( url_com )
  soup = bs(req.content, 'html.parser')
  sc = soup.find_all('div' , id = 'company_info')[0]
  regex_obj = re.compile(r'NSE:\n\D+\n')
  find = regex_obj.search(sc.text)
  stock_code = find.group().split('\n')[1]

  if len(stock_code) != 0 :
    try :
      url = url1 + stock_code +  url2 + url3
      price_data = requests.get(url, headers = header).json()['chart']['result'][0]['indicators']['quote'][0]['close']

    except :
      url = url1 + stock_code + '-ST' + url2 + url3
      price_data = requests.get( url, headers = header).json()['chart']['result'][0]['indicators']['quote'][0]['close']

  adj_price = pd.Series(filter(lambda x : x is not None , price_data))
  if len(adj_price ) > 5 :
    ema = ta.ema( adj_price, length = int(len(price_data)*0.2)  ).iloc[-1]
    if adj_price.iloc[-1] > ema :
      print(stk, 'IS ABOVE ITS EMA')
    else :
      print(stk, 'IS BELOW ITS EMA')

Rulka Electricals IS BELOW ITS EMA
Go Digit General Insurance IS ABOVE ITS EMA
Quest Laboratories IS BELOW ITS EMA
Indian Emulsifiers IS BELOW ITS EMA
ABS Marine Services IS ABOVE ITS EMA
Mandeep Auto Industries Ltd IS ABOVE ITS EMA
Premier Roadlines  IS BELOW ITS EMA
Energy-Mission Machineries India IS ABOVE ITS EMA
Silkflex Polymers IS BELOW ITS EMA
Aadhar Housing Finance IS BELOW ITS EMA
TBO Tek IS BELOW ITS EMA
TGIF Agribusiness IS BELOW ITS EMA
Finelistings Technologies IS BELOW ITS EMA
Winsol Engineers IS BELOW ITS EMA
Refractory Shapes IS ABOVE ITS EMA
Indegene IS ABOVE ITS EMA

In [8]:
"""
plt.title(stk)
plt.figure(figsize = (12,6))
plt.plot(price_data)
plt.xlabel('TICKS')
plt.ylabel('PRICE') """

"\nplt.title(stk)\nplt.figure(figsize = (12,6))\nplt.plot(price_data)\nplt.xlabel('TICKS')\nplt.ylabel('PRICE') "